CREATE TABLE IF NOT EXISTS categories(
	id BIGSERIAL UNIQUE PRIMARY KEY,
  	name VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS products(
	id BIGSERIAL PRIMARY KEY,
  	name VARCHAR(200) UNIQUE NOT NULL,
  	price DECIMAL(8,2) NOT NULL,
  	category_id INTEGER UNIQUE NOT NULL,
  	FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
);